spring.application.name=demo
server.port=8088
management.endpoints.web.exposure.include=*

report.module.url=http://localhost:8080/api/echo

#DB Connection Parameters H2
spring.datasource.url=jdbc:h2:file:${user.dir}/db/${dbName}
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=load_test_helper
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql

#Database Parameters
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1

#Logging parameters
logging.level.root=INFO

#Scheduler Parameters
spring.task.scheduling.pool.size=1

#Global constants
userDir=${user.dir}
serverListFile=serverList.dat
profileListFile=profileList.dat
dbName=website